kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy


spec:
  replicas: 1
  selector:
    matchLabels:
      name: velpod


  template:
    metadata:
      name: velpod
      labels:
        name: velpod


    spec:
      containers:
        - name: vel-1
          image: kunalgkny/payment:1.0
          ports:
            - containerPort: 8080
